### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by marqdevx**

### CODE REVIEW

**Comment by marqdevx** [comment]
Do we need to publish the npm package? 🤔 
As far as I understood, it takes the package from github, isnt it?

**Review by sebromero — CHANGES_REQUESTED** [review]
Please bump the version with `npm version patch` instead

**Comment by sebromero** [comment]
> Do we need to publish the npm package? 🤔 As far as I understood, it takes the package from github, isnt it?

No it gets published to the official npm repo. Once you bump the version, run `npm publish`

**Comment by marqdevx** [comment]
Im getting

> You do not have permission to publish "content-lint". Are you logged in as the correct user?

**Comment by sebromero** [comment]
@marqdevx Looks like I need to do it.

**Comment by marqdevx** [comment]
Yup :)

**Pull request closed without merging**
